<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WolfIsland</AssemblyName>
    <RootNamespace>WolfIsland</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

</Project>
